import Link from "next/link";

export const metadata = {
  title: "Next Template | Home",
  description: "Generated by create next app by Sahin Alam",
};

export default function Home() {
  return (
    <div
      style={{
        height: "500px",
        width: "500px",
      }}
    >
      <h1>Home page</h1>
      <Link href="/about">About</Link>
      <br />
      <Link href="/team">Team Page</Link> <br />
      <Link href="/developers">Developers Page</Link>
      <br />
      <Link href="/feedback">Feedback Page</Link>
    </div>
  );
}
