import Link from "next/link";
 import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
export const metadata = {
  title: "Next Template | Home",
  description: "Generated by create next app by Sahin Alam",
};

export default function Home() {
  return (
    <div
      // style={{
      //   height: "500px",
      //   width: "500px",
      // }}
    >
      <Navbar/>
      <Footer/>
      <h1>Home page</h1>
      <Link href="/about">About</Link>
    </div>
  );
}
