import Link from "next/link";

export const metadata = {
  title: "Next Template | Home",
  description: "Generated by create next app by Sahin Alam",
};

export default function Home() {
  return (
    <div
      style={{
        height: "500px",
        width: "500px",
      }}
    >
      <h1>Home page</h1>
      <div style={{ display: "flex", flexDirection: "column" }}>
        <Link href="/about">About</Link>
        <Link href="/signIn">Sign in</Link>
        <Link href="/signUp">Sign up</Link>
      </div>
    </div>
  );
}
